// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBcGiaETkdX4-Q5smjucUet0boe21sWA',
    appId: '1:1043839855571:web:85b60d2dd80b32a98e9d26',
    messagingSenderId: '1043839855571',
    projectId: 'al-lok-dal-lok',
    authDomain: 'al-lok-dal-lok.firebaseapp.com',
    storageBucket: 'al-lok-dal-lok.firebasestorage.app',
    measurementId: 'G-5FQMNYLCHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9IYLM51DXCPjYczoM9fSIxRmNHMWf34',
    appId: '1:1043839855571:android:860099cc4ef9f8bc8e9d26',
    messagingSenderId: '1043839855571',
    projectId: 'al-lok-dal-lok',
    storageBucket: 'al-lok-dal-lok.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA228uuE6rkJIHkcwoLBdU9Xt_T132YuA',
    appId: '1:1043839855571:ios:4337f3e8702da84c8e9d26',
    messagingSenderId: '1043839855571',
    projectId: 'al-lok-dal-lok',
    storageBucket: 'al-lok-dal-lok.firebasestorage.app',
    iosBundleId: 'com.saessak.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA228uuE6rkJIHkcwoLBdU9Xt_T132YuA',
    appId: '1:1043839855571:ios:4337f3e8702da84c8e9d26',
    messagingSenderId: '1043839855571',
    projectId: 'al-lok-dal-lok',
    storageBucket: 'al-lok-dal-lok.firebasestorage.app',
    iosBundleId: 'com.saessak.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBcGiaETkdX4-Q5smjucUet0boe21sWA',
    appId: '1:1043839855571:web:7530ceedb97468de8e9d26',
    messagingSenderId: '1043839855571',
    projectId: 'al-lok-dal-lok',
    authDomain: 'al-lok-dal-lok.firebaseapp.com',
    storageBucket: 'al-lok-dal-lok.firebasestorage.app',
    measurementId: 'G-W1Y5D45PEC',
  );
}
